name: yet_another_wallpaper_app
description: Just another app that provides beautiful wallpapers from Unsplash
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  bloc: ^0.11.2
  built_collection: ^4.2.0
  built_value: ^6.4.0
  cupertino_icons: ^0.1.2
  dio: ^2.1.2
  equatable: ^0.2.3
  flutter:
    sdk: flutter
  flutter_advanced_networkimage: ^0.4.15
  flutter_bloc: ^0.10.0
  rxdart: ^0.21.0

dev_dependencies:
  build_runner: ^1.3.1
  built_value_generator: ^6.4.0
  flutter_test:
    sdk: flutter
  test: ^1.6.1

flutter:
  uses-material-design: true
