name: yet_another_wallpaper_app
description: Just another app that provides beautiful wallpapers from Unsplash
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_collection: ^4.1.0
  built_value: ^6.3.2
  cupertino_icons: ^0.1.2
  dio: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.2.8
  built_value_generator: ^6.3.2
  flutter_test:
    sdk: flutter
  test: ^1.5.3

flutter:
  uses-material-design: true
